---
language: node_js
sudo: false
dist: trusty
node_js: 'lts/*'

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  global:
    - MOZ_HEADLESS=1
  matrix:
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-1.13
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm --version

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - node node-tests/**/*-test.js
  - npx ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
